INSERT INTO EquipmentTypes (name) VALUES
('Microscope'),
('Centrifuge'),
('PCR Machine'),
('Spectrophotometer'),
('Gas Chromatograph'),
('Laser Cutter'),
('3D Printer'),
('Oscilloscope'),
('Thermocycler'),
('Electrochemical Analyzer'),
('Atomic Absorption Spectrometer'),
('X-Ray Diffractometer'),
('NMR Spectrometer'),
('Wind Tunnel'),
('Tensile Testing Machine'),
('Incubator'),
('Water Bath'),
('Magnetic Stirrer'),
('Mass Spectrometer'),
('UV-Vis Spectrometer');
